### ISSUE TITLE
simplify VM response object

### ISSUE THREAD

**Issue by lukewhrit** [BasedDevelopment/eve#27]
currently there's a redundant `hypervisor` field at the top of the VM object, we should remove this and replace it with the `hv` field inside the current `vm` object and move that (`vm`) to be top level.

**Comment by lukewhrit** [comment]
eve also needs to, in general, return back more information about the VM/HV, i.e. disk image, CPU, etc.

**Comment by ericzty** [comment]
> eve also needs to, in general, return back more information about the VM/HV, i.e. disk image, CPU, etc.

The more info can be fetched via /virtual_machines/vmid
or /virtual_machines/vmid/state

this is so that we can save the data pulled when the user is just browsing the list of VMs available and not actually need VM details.
